name: 'healthcare_analytics'
version: '1.0.0'
config-version: 2

profile: 'healthcare_analytics'

# Directory layout
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  healthcare_analytics:
    # Staging models: views by default, reads from Silver CSVs or Silver tables
    staging:
      +materialized: view
      +schema: staging

    # Mart / Gold models: tables, partitioned for BI tool performance
    marts:
      +materialized: table
      +schema: gold

    # Explicit Gold model folder used alongside marts
    gold:
      +materialized: table
      +schema: gold
